# Generated by Django 2.2.7 on 2019-11-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_auto_20191127_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
